"""Safe synthetic fixture identifiers for identity and access tests."""

from __future__ import annotations

from typing import Final

SYNTHETIC_FIXTURE_IDS: Final[tuple[str, ...]] = (
    "FX-IA-PROVIDER-FIRST-TELEGRAM-001",
    "FX-IA-PROVIDER-FIRST-MAX-001",
    "FX-IA-SAME-PROVIDER-REPLAY-001",
    "FX-IA-WEAK-SIGNAL-NO-MERGE-001",
    "FX-IA-LINK-CHALLENGE-CREATED-001",
    "FX-IA-LINK-CHALLENGE-EXPIRED-001",
    "FX-IA-LINK-CHALLENGE-REPLAY-001",
    "FX-IA-LINK-FOREIGN-ACCOUNT-REJECTED-001",
    "FX-IA-PHONE-CONTACT-OPTIONAL-001",
    "FX-IA-EMAIL-CHALLENGE-CODE-REDACTED-001",
    "FX-IA-ROLE-ASSIGNMENT-AUTHORIZED-001",
    "FX-IA-ROLE-ASSIGNMENT-FORBIDDEN-001",
    "FX-IA-SESSION-REVOKED-001",
    "FX-IA-MERGE-BLOCKED-OD008-001",
)

__all__ = ["SYNTHETIC_FIXTURE_IDS"]
