"""Entitlements and Billing module package."""

from mayak.platform.boundaries import ENTITLEMENTS_AND_BILLING_MODULE_ID

from .contracts import (
    ACCOUNT_ID_OWNERSHIP_SCOPE,
    ActorContext,
    EffectiveEntitlementDecision,
    EffectiveInterval,
    EntitlementDecisionStatus,
    EntitlementGrant,
    ManualAccessGrant,
    ManualAccessGrantState,
    PaymentEvent,
    PaymentEventState,
    PaymentRecord,
    PaymentRecordState,
    Subscription,
    SubscriptionState,
    TariffDefinition,
    TariffName,
)
from .fixtures import (
    FIXTURE_IDS,
    FOREIGN_ACCOUNT_FORBIDDEN,
    LIMIT_ALLOW,
    LIMIT_DENY,
    MANUAL_GRANT_AUTHORIZED,
    MANUAL_GRANT_EXPIRED,
    MANUAL_GRANT_MISMATCH,
    MANUAL_GRANT_REPLAY,
    NO_FABRICATED_TARIFF,
    OWN_ACCOUNT_DECISION,
    PAYMENT_NOT_ENTITLEMENT,
    REDACTION,
    SYNTHETIC_FIXTURE_BY_ID,
    SYNTHETIC_FIXTURE_CASES,
    SyntheticFixtureCase,
)
from .policies import (
    APPROVED_TARIFF_DEFINITIONS,
    BASIC_TARIFF_POLICY,
    FREE_TARIFF_POLICY,
    FUTURE_DECISION_GATES,
    TARIFFS_BY_NAME,
)

MODULE_ID = ENTITLEMENTS_AND_BILLING_MODULE_ID

__all__ = [
    "ACCOUNT_ID_OWNERSHIP_SCOPE",
    "APPROVED_TARIFF_DEFINITIONS",
    "ActorContext",
    "BASIC_TARIFF_POLICY",
    "EffectiveEntitlementDecision",
    "EffectiveInterval",
    "EntitlementDecisionStatus",
    "EntitlementGrant",
    "FIXTURE_IDS",
    "FREE_TARIFF_POLICY",
    "FUTURE_DECISION_GATES",
    "FOREIGN_ACCOUNT_FORBIDDEN",
    "LIMIT_ALLOW",
    "LIMIT_DENY",
    "ManualAccessGrant",
    "ManualAccessGrantState",
    "MANUAL_GRANT_AUTHORIZED",
    "MANUAL_GRANT_EXPIRED",
    "MANUAL_GRANT_MISMATCH",
    "MANUAL_GRANT_REPLAY",
    "MODULE_ID",
    "NO_FABRICATED_TARIFF",
    "OWN_ACCOUNT_DECISION",
    "PaymentEvent",
    "PaymentEventState",
    "PaymentRecord",
    "PaymentRecordState",
    "PAYMENT_NOT_ENTITLEMENT",
    "REDACTION",
    "SYNTHETIC_FIXTURE_BY_ID",
    "SYNTHETIC_FIXTURE_CASES",
    "Subscription",
    "SubscriptionState",
    "SyntheticFixtureCase",
    "TARIFFS_BY_NAME",
    "TariffDefinition",
    "TariffName",
]
