"""MAX Adapter module package."""

# ruff: noqa: E501

from mayak.platform.boundaries import MAX_ADAPTER_MODULE_ID

from .contracts import (
    MaxAccountLinkReference,
    MaxAdapterReadModel,
    MaxCommandEnvelope,
    MaxCommandNormalizationState,
    MaxCommandSourceKind,
    MaxCommandSurfaceKind,
    MaxContactValidationResult,
    MaxContactValidationState,
    MaxEligibilityEvidenceReference,
    MaxEligibilityState,
    MaxMiniAppValidationResult,
    MaxMiniAppValidationState,
    MaxOutboundRequest,
    MaxOutboundRequestState,
    MaxProviderIdentity,
    MaxProviderOutcome,
    MaxProviderOutcomeState,
    MaxReconciliationRecord,
    MaxReconciliationState,
    MaxRetryRecommendation,
    MaxUpdateAdmissionState,
    MaxUpdateDeduplicationRecord,
    MaxUpdateDeduplicationState,
    MaxUpdateIntakeRecord,
    MaxUpdateIntakeState,
    MaxUpdateSourceKind,
    MaxUpdateStructuralClass,
)
from .mini_app import MaxMiniAppValidation, validate_webapp_data
from .runtime import (
    MaxAdapterRuntime,
    MaxDeliveryMappingResult,
    MaxIdentityConflict,
    MaxIdentityMappingResult,
    MaxInputRejected,
    MaxIntakeOutcome,
    MaxIntakeResult,
    MaxNonceResult,
    MaxReadiness,
    MaxRuntimeError,
    max_readiness,
    webhook_authenticity,
)
from .transport import (
    FakeMaxTransport,
    HttpxMaxTransport,
    MaxTransportClass,
    MaxTransportResult,
    MaxUpdateBatch,
)

MODULE_ID = MAX_ADAPTER_MODULE_ID

__all__ = [
    "MODULE_ID",
    "MaxAccountLinkReference",
    "MaxAdapterReadModel",
    "MaxCommandEnvelope",
    "MaxCommandNormalizationState",
    "MaxCommandSourceKind",
    "MaxCommandSurfaceKind",
    "MaxContactValidationResult",
    "MaxContactValidationState",
    "MaxEligibilityEvidenceReference",
    "MaxEligibilityState",
    "MaxMiniAppValidationResult",
    "MaxMiniAppValidationState",
    "MaxOutboundRequest",
    "MaxOutboundRequestState",
    "MaxProviderIdentity",
    "MaxProviderOutcome",
    "MaxProviderOutcomeState",
    "MaxReconciliationRecord",
    "MaxReconciliationState",
    "MaxRetryRecommendation",
    "MaxUpdateDeduplicationRecord",
    "MaxUpdateDeduplicationState",
    "MaxUpdateIntakeRecord",
    "MaxUpdateIntakeState",
    "MaxUpdateAdmissionState",
    "MaxUpdateSourceKind",
    "MaxUpdateStructuralClass",
    "MaxAdapterRuntime",
    "MaxDeliveryMappingResult",
    "MaxIdentityConflict",
    "MaxIdentityMappingResult",
    "MaxInputRejected",
    "MaxIntakeOutcome",
    "MaxIntakeResult",
    "MaxNonceResult",
    "MaxReadiness",
    "MaxRuntimeError",
    "max_readiness",
    "webhook_authenticity",
    "FakeMaxTransport",
    "HttpxMaxTransport",
    "MaxTransportClass",
    "MaxTransportResult",
    "MaxUpdateBatch",
    "MaxMiniAppValidation",
    "validate_webapp_data",
]
