"""Error category primitives for public contracts."""

from enum import Enum


class ErrorCategory(str, Enum):
    INVALID_ARGUMENT = "INVALID_ARGUMENT"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    PRECONDITION_FAILED = "PRECONDITION_FAILED"
    CONFLICT = "CONFLICT"
    IDEMPOTENCY_MISMATCH = "IDEMPOTENCY_MISMATCH"
    RATE_LIMITED = "RATE_LIMITED"
    EXTERNAL_UNAVAILABLE = "EXTERNAL_UNAVAILABLE"
    EXTERNAL_REJECTED = "EXTERNAL_REJECTED"
    EXTERNAL_AMBIGUOUS = "EXTERNAL_AMBIGUOUS"
    TEMPORARY_FAILURE = "TEMPORARY_FAILURE"
    INTERNAL_FAILURE = "INTERNAL_FAILURE"
