"""Egress Routing module package."""

from mayak.platform.boundaries import EGRESS_ROUTING_MODULE_ID

from .contracts import (
    AgentLifecycleStatus,
    DiagnosticEvidenceKind,
    DispatchAttempt,
    DispatchStatus,
    EgressAgent,
    EgressRoute,
    PolicyBasedFallbackDecision,
    PolicyBasedFallbackStatus,
    RouteCapability,
    RouteEvidenceReference,
    RouteEvidenceStatus,
    RouteFamily,
    RouteHealthState,
    RouteHealthStatus,
    RouteLease,
    RouteLeaseStatus,
    RouteLifecycleStatus,
    RouteQuarantineDecision,
    RouteQuarantineStatus,
    RouteReadinessDecision,
    RouteReadinessStatus,
    RouteReconciliationState,
    RouteReconciliationStatus,
    RouteRestrictionState,
    RouteRestrictionStatus,
    RouteSelectionDecision,
    RouteSelectionStatus,
    SafeOperationalDiagnostic,
    SessionPolicyStatus,
    TransportAssignment,
    TransportAssignmentOutcome,
    TransportOutcomeStatus,
)
from .fixtures import (
    EGRESS_SYNTHETIC_FIXTURE_IDS,
    EGRESS_SYNTHETIC_FIXTURES,
    ER02_TASK_ID,
    EgressSyntheticFixture,
)

MODULE_ID = EGRESS_ROUTING_MODULE_ID

__all__ = (
    "MODULE_ID",
    "AgentLifecycleStatus",
    "DiagnosticEvidenceKind",
    "DispatchAttempt",
    "DispatchStatus",
    "EgressAgent",
    "EgressRoute",
    "PolicyBasedFallbackDecision",
    "PolicyBasedFallbackStatus",
    "RouteCapability",
    "RouteEvidenceReference",
    "RouteEvidenceStatus",
    "RouteFamily",
    "RouteHealthState",
    "RouteHealthStatus",
    "RouteLease",
    "RouteLeaseStatus",
    "RouteLifecycleStatus",
    "RouteQuarantineDecision",
    "RouteQuarantineStatus",
    "RouteReadinessDecision",
    "RouteReadinessStatus",
    "RouteReconciliationState",
    "RouteReconciliationStatus",
    "RouteRestrictionState",
    "RouteRestrictionStatus",
    "RouteSelectionDecision",
    "RouteSelectionStatus",
    "SafeOperationalDiagnostic",
    "SessionPolicyStatus",
    "TransportAssignment",
    "TransportAssignmentOutcome",
    "TransportOutcomeStatus",
    "ER02_TASK_ID",
    "EGRESS_SYNTHETIC_FIXTURE_IDS",
    "EGRESS_SYNTHETIC_FIXTURES",
    "EgressSyntheticFixture",
)
